/**
  ***************************************************************************** 
  * @title   ACMPCompare.c
  * @author  CooCox
  * @date    23 Feb 2012
  * @brief   This example is to select The comparator reference pin CPN0 is s
  *          elected as the negative comparator input, Enable CMP0 interrupt 
  *          function, the interrupt will happen whenever the comparator0 out
  *          put changes state.
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

#include "xhw_types.h"
#include "xhw_memmap.h"
#include "xhw_ints.h"
#include "xsysctl.h"
#include "xgpio.h"
#include "xcore.h"
#include "xacmp.h"

unsigned long user_Callback(void *pvCBData,  unsigned long ulEvent,
                                       unsigned long ulMsgParam,void *pvMsgData);

//*****************************************************************************
//
//! Ininite the acmp 
//!
//! \param None
//!
//! This function ininite the ACMP including clock source and enable ACMP 
//!
//! \return none
//
//*****************************************************************************
void ACMPCompare(void)
{
    //
    // Set SysClk 36MHz using Extern 12M oscillator
    //
    xSysCtlClockSet(12000000, xSYSCTL_OSC_MAIN | xSYSCTL_XTAL_12MHZ);
    
    //
    // Enable Peripheral SPI0
    //
    xSysCtlPeripheralEnable(xSYSCTL_PERIPH_ACMP0);
    
    //
    // Configure the ACMP pin
    //
    xSPinTypeACMP(CMP0IN0, PC6);
    xSPinTypeACMP(CMP0IN1, PC7);
    xSPinTypeACMP(CMP0IN2, PC8);
    
    //
    // Congigure Comp-(Analog source negative input) is CPN pin
    //
    xACMPConfigure(xACMP0_BASE, 0, xACMP_ASRCN_PIN_IN0);
    xACMPConfigure(xACMP0_BASE, 0, xACMP_ASRCN_PIN_IN1);
    
    //
    // Configure the INT 
    //
    xACMPIntCallbackInit( xACMP0_BASE, 0, user_Callback );
    xACMPIntEnable( xACMP0_BASE, 0 );	
    xIntEnable( xINT_ACMP0 );

    //
    // Enable ACMP
    //
    xACMPEnable( xACMP0_BASE, 0 );    
}

//*****************************************************************************
//
//! \brief ACMP callback interrupt
//!
//! \param None
//!
//! \return none
//
//*****************************************************************************
unsigned long user_Callback(void *pvCBData,  unsigned long ulEvent,
                                       unsigned long ulMsgParam,void *pvMsgData)
{
    //
    // add your own code
    //
    //...
  
    return 0;
}