#ifndef _NUC4XX_COX_BASE_H_
#define _NUC4XX_COX_BASE_H_

#include "sysctl.h"
#include "gpio.h"
#include "uart.h"
#include "spi.h"
#include "i2c.h"

#define SYSCTL_PERIPH_IOPA      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPB      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPC      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPD      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPE      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPF      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPG      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPH      SYSCTL_PERIPH_GPIO
#define SYSCTL_PERIPH_IOPI      SYSCTL_PERIPH_GPIO

#define SYSCTL_PERIPH_DMA0      SYSCTL_PERIPH_PDMA

#endif
