/**
  ***************************************************************************** 
  * @title   ADConvert.c
  * @author  CooCox
  * @date    23 Feb 2012
  * @brief   This example is to configure the ADC Channel0 as Single cycle sc
  *          an mode, enable the end of convert interrupt, save the convert v
  *          alue and read the conversion value length.
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

#include "xhw_types.h"
#include "xhw_memmap.h"
#include "xhw_ints.h"
#include "xsysctl.h"
#include "xgpio.h"
#include "xcore.h"
#include "xadc.h"


unsigned long ADCCallback(void *pvCBData,  unsigned long ulEvent,
                                       unsigned long ulMsgParam,void *pvMsgData);

//*****************************************************************************
//
//! Ininite the ADC 
//!
//! \param None
//!
//! This function ininite the ADC including clock source and enable ADC 
//!
//! \return none
//
//*****************************************************************************
void ADConvert(void)
{
  
    unsigned long ulValueLength;
    unsigned long ulData[10];
    //
    // Set SysClk 36MHz using Extern 12M oscillator
    //
    xSysCtlClockSet(12000000, xSYSCTL_OSC_MAIN | xSYSCTL_XTAL_12MHZ);
    
    //
    // Enable Peripheral SPI0
    //
    xSysCtlPeripheralEnable(SYSCTL_PERIPH_ADC);
    
    //
    // Configure Some GPIO pins as SPI Mode
    //
    xSPinTypeADC(ADC0, PE20);
    
    //
    // ADC Channel0 convert once, Software tirgger.
    //
    xADCConfigure(xADC0_BASE, xADC_MODE_SCAN_SINGLE_CYCLE, ADC_TRIGGER_PROCESSOR);
    
    //
    // Enable the channel0
    //
    xADCStepConfigure(xADC0_BASE, 1, xADC_CTL_CH0); 
      
    //
    // Enable the ADC end of conversion interrupt
    //  
    xADCIntEnable(xADC0_BASE, xADC_INT_END_CONVERSION);  
    
    //
    // install the call back interrupt
    //
    xADCIntCallbackInit(xADC0_BASE, ADCCallback);
    
    //
    // Enable the NVIC ADC interrupt
    //
    xIntEnable(xINT_ADC0);
    
    //
    // Enable the adc
    //
    ADCSingleEndedChannelEnable(xADC0_BASE, 0);
    
    //
    // Read the convert value
    //
    ulValueLength = xADCDataGet(xADC0_BASE, ulData);

}

//*****************************************************************************
//
//! \brief ADC callback interrupt
//!
//! \param None
//!
//! \return none
//
//*****************************************************************************
unsigned long ADCCallback(void *pvCBData,  unsigned long ulEvent,
                                       unsigned long ulMsgParam,void *pvMsgData)
{
    //
    // add your own code
    //
    //...
  
    return 0;
}